# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Windows and MacOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-11]
        arch: [x64, arm64]
        exclude:
          # Not supported yet by GitHub Actions
          - os: windows-2022
            arch: arm64
          # - os: windows-2022
          #   arch: x64
          # - os: macos-11
          #   arch: x64
          # - os: macos-11
          #   arch: arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore --arch ${{ matrix.arch }}
        working-directory: GetAssemblyInfo

      - name: Publish
        run: dotnet publish --no-restore --self-contained --arch ${{ matrix.arch }} -c Release -o ../output
        working-directory: GetAssemblyInfo

      - uses: actions/upload-artifact@v4
        with:
          name: GetAssemblyInfo-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/output/GetAssemblyInfo
            ${{ github.workspace }}/output/GetAssemblyInfo.exe
